config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :trips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "application#home"

  # get 'current_user' => "users#current_user"

   resources :users, only: [:new, :show] do
    # nested resource for trips
     resources :trips, only: [:show, :index]
   end


    # nested resource for reviews
    resources :users, only: [:new, :show] do
      resources :reviews, only: [:new, :edit, :show, :index]
   end
  resources :users
  resources :meals
  resources :orders, only: [:new, :destroy]

  get '/auth/facebook/callback' => 'sessions#create'

  get '/auth/failure' => 'sessions#failure'

  get '/most_popular', to: 'meals#most_popular'

  get '/signin', to: 'sessions#signin'
  post '/signin', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

   get '/add_meal', to: 'orders#add_meal'
  get'/checkout', to: 'trips#checkout'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :trips
  has_many :reviews

  before_save :named

    validates_uniqueness_of :email
    validates :email, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }
    validates_presence_of :first_name, :last_name, :email, :password
    validates :first_name, :last_name,  length: { minimum: 3 }
    validates :password,  length: { in: 6..20 }

    def named
      if self.first_name
        "#{self.first_name.titleize} #{self.last_name.titleize}"
      else
        self.name
      end
    end


    private

    # def make_title_case
    #   if self.name
    #   self.name = self.name.titleize
    # else
    #   self.name =self.first_name.titleize
    # end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

  def index
    if  is_admin? || !current_user
      @users = User.all
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @users}
      end
    else
      redirect_to :root
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      # redirect_to new_trip_path
      respond_to do |format|
        format.html { redirect_to new_trip_path }
        format.json { render json: @user}
      end
    else
      render :new
    end
  end

  def edit
    if !is_admin?
    @user = User.find(params[:id])
    render 'edit'
  else
    redirect_to meals_path
end
  end

  def update
    @user = User.find(params[:id])
    @user = User.update(user_params)
    respond_to do |format|
      format.html { redirect_to user_path }
      format.json { render json: @user}
    end
    # redirect_to user_path
  end

  def show
    respond_to do |format|
      if is_admin?
       @user = User.find(params[:id])
         format.html { render :show }
         format.json  { render json: @user}
     elsif !is_admin? && current_user
         # @user = User.find(session[:user_id])
         @user = User.find(session[:user_id])
         format.html { render :show }
         format.json  { render json: @user }

     else
       redirect_to meals_path
     end

  end
end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <% if @user.errors.any? %>
    <li><%= msg %></li>
    <% end %>
    </ul>

    </div>
    <% end %>
    <% end %>

app/views/users/_form.html.erb
<%= render 'errors' %>


<%= f.label :first_name %>
<%= f.text_field :first_name %> <br>
<%= f.label :last_name %>
<%= f.text_field :last_name %> <br>
<%= f.label :email %>
<%= f.email_field :email %> <br>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<p class="form-title"><h1>Edit Account</h1></p>
<%= render 'form', :f => f %>

<%= f.submit "Edit Account" %>
<% end %>

app/views/users/index.html.erb
<h1>Customer List</h1>

<% @users.each do |c| %>
    <% if !c.admin %>
  Name: <%= c.named %> <br>

  Email: <%= c.email %> <br>

  <%if c.trips %>
  Orders: <br>
  <% c.trips.each do |trip| %>
    Date: <%= link_to (trip.date).strftime("%m/%d/%Y"), user_trip_path(c.id, trip.id) %>
    Total: <%= number_to_currency(trip.total)  %> <br>
    Comment: <%=  trip.comment if trip.comment %> <br>
    <% end %>
    <% end %>
    <hr>
    <% end %>
  <% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <p class="form-title">Create An Account</p>
  <%= render 'form', :f => f %>
<% end %>

app/views/users/show.html.erb
<%# if @user.first_name%>
<div class="user">
<h1>Account Information: <%= @user.named %>

<h3>Email: <%= @user.email %> <%= link_to "| Edit Account", edit_user_path(@user) if @user == current_user %></h3><br>


<h4 id="userOrders"  style="color: blue;" >Orders</h4>

<div id="orders" style="display: none; "></div>




<!-- All removed for jquery project -->
<%# @user.trips.each do |trip| if !trip.meals.empty? %>

  <!-- <%# "Order No. #{trip.id}"%> | -->
  <!-- <%# "Date: #{trip.date.strftime("%m/%d/%y, %l:%M %p")}"  if !trip.meals.empty?%> <br> -->

  <%#trip.meals.each do |meal| %>
  <!-- Meal: <%# meal.name %> <br>
  Price: <%# number_to_currency(meal.price) %> <br> -->
  <%# end %>
  <%# end %>

   <%# "Order Total:  #{number_to_currency(trip.total)}" if !trip.meals.empty? %>
   <!-- <br> <br> -->
<%# end %>

<br> <br>
</div>