config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :trips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "application#home"

  # get 'current_user' => "users#current_user"

   resources :users, only: [:new, :show] do
    # nested resource for trips
     resources :trips, only: [:show, :index]
   end


    # nested resource for reviews
    resources :users, only: [:new, :show] do
      resources :reviews, only: [:new, :edit, :show, :index]
   end
  resources :users
  resources :meals
  resources :orders, only: [:new, :destroy]

  get '/auth/facebook/callback' => 'sessions#create'

  get '/auth/failure' => 'sessions#failure'

  get '/most_popular', to: 'meals#most_popular'

  get '/signin', to: 'sessions#signin'
  post '/signin', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

   get '/add_meal', to: 'orders#add_meal'
  get'/checkout', to: 'trips#checkout'
end

app/models/meal.rb
class Meal < ApplicationRecord

  has_many :orders
  has_many :trips, through: :orders
  validates :name, :description, :price, :category, presence: true
  scope :low_cal, -> { where("calorie_count <= ?", 375) }


  def self.by_category(category)
    where(category: category)
  end

  def self.meal_count
    # meals = joins(:trips).group(:name).count

    sql = "SELECT meals.name, COUNT(meals.name) AS total FROM trips
    LEFT OUTER JOIN orders
    ON orders.trip_id = trips.id
    LEFT OUTER JOIN meals
    ON orders.meal_id = meals.id
    GROUP BY meals.name
    ORDER BY total DESC
    LIMIT 1".
    result = ActiveRecord::Base.connection.execute(sql)
    result = result[0]
    name = result['name']
    total = result['total']

    puts name
    puts total
    # meals = joins(:trips).select("COUNT(name) AS total").group(:name)
    # raise records_array
    # puts records_array
    # meals.first.total
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)

      if @meal.save
        session[:meal_id] = @meal.id
        respond_to do |format|

      # redirect_to meals_path
          # format.html { redirect_to meal_path(@meal) }
        format.json  { render json: @meal, status: 201} #{ render json: @meals}
      end
    else
      render :new

    end
  end

  # def most_popular
  #   @meal = Meal.meal_count
  # end

  def index

    if !params[:category].blank? && !params[:calorie_count].blank?
      @meals = Meal.by_category(params[:category]).low_cal
    elsif !params[:category].blank? && params[:calorie_count].blank?
      @meals = Meal.by_category(params[:category])
     elsif  !params[:calorie_count].blank?
       @meals = Meal.low_cal
    else
    # if no filters are applied, show all posts
    @meals = Meal.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @meals}
    end

    end
  end



  def show
    @meal = Meal.find(params[:id])
    session[:meal_id] = @meal.id
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @meal, status: 200}
    end
    # render json: @meal, status: 200
  end

  def edit
    if current_user.admin == true
    @meal = Meal.find(params[:id])
    render :edit
  else
    redirect_to meals_path
    end
  end

  def update
     # binding.pry
    @meal = Meal.find(params[:id])
    @meal.update(meal_params)
    respond_to do |format|
      format.html { redirect_to meals_path }
      format.json { render json: @meal}
    end

    # redirect_to meal_path(@meal)
  end

  def destroy
    @meal = Meal.find(params[:id])

    if current_user.admin
    @meal.destroy
    redirect_to meals_path
    end
  end



private

      def meal_params
         params.require(:meal).permit(:name, :price, :category, :calorie_count, :description)
       end
      end

app/helpers/meal_helper.rb
module MealHelper
end

app/views/meals/_errors.html.erb
<% if @meal.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@meal.errors.count, "error") %>
      prohibited this meal from being saved:
    </h2>

    <ul>
    <% @meal.errors.full_messages.each do |msg| %>
    <% if @meal.errors.any? %>
    <li><%= msg %></li>
    <% end %>
    </ul>

    </div>
    <% end %>
    <% end %>

app/views/meals/_form.html.erb
<%= render 'errors' %>

<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :calorie_count%>
<%= f.text_field :calorie_count  %> <br>
<%= f.label :description %>
<%= f.text_area :description %> <br>
<%= f.label :price%>
<%= f.number_field :price, :class => 'text_field', :step => 0.05 %> <br>
<%= f.label :category%>
<%= f.select :category, Meal.all.collect{|u| [u.category]}.uniq %> <br>
<%# f.text_field :category, list: "categories_autocomplete" %>
  <!-- <datalist id="categories_autocomplete"> -->
    <%# Meal.all.each do |u| %>
    <!-- <option value="<%# u.category %>"> -->
    <%# end %>
  <!-- </datalist> -->

<%= f.submit  %>

app/views/meals/edit.html.erb
<%= form_for @meal do |f| %>

<%= render 'form', :f => f  %>
<% end %>

app/views/meals/index.html.erb
<div class="meals">
    <h1>Menu</h1> <br>



    <div class = "filter">
      <%= form_tag("/meals", method: "get") do %>
        Category <%= select_tag "category", options_for_select(["Main", "Side", "Dessert", "Drink"]), include_blank: true %>
        Low Calorie <%= select_tag "calorie_count", options_for_select(["Low Cal"]), include_blank: true %>
        <%= submit_tag "Filter" %>
      <% end %>
    </div> <br>

  <table id="meals">
    <tr>
      <!-- <th onclick="getMeals()">Meal</th> -->
      <th >Meal</th>
      <th>Price</th>
      <th><% %></th>
    </tr>
  <% @meals.each do |meal| if @meals %>
    <tr id="meals-list">
      <td><b><%= link_to meal.name,  meal_path(meal), class: 'descrip' %></b></td>
       <td><%= number_to_currency(meal.price) %></td>
       <td ></td>
      <% if current_user && current_user.admin %>
      <td> <%= link_to "Delete", meal, method: :delete  %> | <%= link_to "Edit", edit_meal_path(meal)  %>  |  <%= link_to "Show", meal_path(meal)  %></td>

        <% end %>
        <% end %>
    </tr>
    <tr><td class= "mealDescription-<%= meal.id  %>" style="display: none;"></td></tr>

  <% end %>
</table>
</div>

app/views/meals/most_popular.html.erb
<h1>Most Popular Meal</h1>
<h2><%= @meal %></h2>

app/views/meals/new.html.erb
<%= form_for @meal, :html=> { class: 'form-meal' } do |f| %>
<p class="form-title">Add New Meal</p>
<%= render 'form', :f => f %>

<% end %>

<div id="mealResult" style="text-align: center">
  
</div>

app/views/meals/show.html.erb
  <div class="meal">
  <div >
    <a  style="font-size: 18px; color: red;" href="#" class="js-prev" data-id="<%=@meal.id%>"><= Previous </a>
    <a  style="font-size: 18px; color: red;" href="#" class="js-next" data-id="<%=(@meal.id) %>"> Next =></a>
  </div>


  <h1 id="mealName"><%= @meal.name %>  </h1>

<h3 id="mealDescription"><%= @meal.description %>  </h3>

<h4 id="mealPrice"> Price: <%= number_to_currency(@meal.price) %>  </h4>
<h4 id="mealCalories"> <%= @meal.calorie_count %> Calories </h4>

<!-- Removed edit functionality from show page bc when next/prev included edit was pilling the wrong params[:id] -->
<!-- <h4><%# link_to "Edit", edit_meal_path(@meal) if current_user && is_admin?  %></h4> -->

 <br>

<%= link_to "Add to Order", new_order_path %><br> <br>
</div>